apiVersion: apps/v1
kind: Deployment
metadata:
   name: webappdeploy
spec:
   replicas: 2
   selector: 
      matchLabels:
        app: mywebapp
   template:
     metadata:
       labels:
         app: mywebapp
     spec:
       containers:
       - name: webappcont
         image: gauravsun/customwebapp
         ports:
         - containerPort: 80
